import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export default StyleSheet.create({
  card: {
    marginHorizontal: 20,
    borderWidth: 3,
    borderColor: COLORS.ink,
    backgroundColor: COLORS.paper,
    marginBottom: 13,
    shadowColor: COLORS.red,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },
  heading: {
    backgroundColor: COLORS.ink,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 3,
    borderBottomColor: COLORS.ink,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  number: {
    color: COLORS.yellow,
    fontFamily: "Courier New",
    fontWeight: "900",
    fontSize: 11,
  },
  name: {
    color: "#fff",
    fontFamily: "Anton_400Regular",
    fontSize: 21,
    letterSpacing: 0.4,
  },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  fieldCell: {
    width: "50%",
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: COLORS.ink,
    position: "relative",
    justifyContent: "center",
  },
  match: { backgroundColor: "#e2f1e5" },
  miss: { backgroundColor: COLORS.paper },
  fieldLabel: {
    color: COLORS.muted,
    fontFamily: "Courier New",
    fontWeight: "700",
    fontSize: 9,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  fieldValue: {
    color: COLORS.ink,
    fontFamily: "Georgia",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 16,
    paddingRight: 28,
    marginTop: 0,
  },
  badge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
});
