import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export default StyleSheet.create({
  area: { zIndex: 2, marginHorizontal: 20, marginBottom: 20 },
  label: {
    color: COLORS.yellow,
    fontFamily: "Anton_400Regular",
    fontSize: 14,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  inputWrap: {
    height: 54,
    borderWidth: 3,
    borderColor: COLORS.ink,
    backgroundColor: COLORS.paper,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    shadowColor: COLORS.blue,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  icon: { marginRight: 10 },
  input: {
    flex: 1,
    color: COLORS.ink,
    fontFamily: "Georgia",
    fontWeight: "700",
    fontSize: 16,
    paddingVertical: 10,
    outlineStyle: "none",
  },
  suggestions: {
    borderWidth: 3,
    borderTopWidth: 0,
    borderColor: COLORS.ink,
    backgroundColor: COLORS.paper,
  },
  suggestion: {
    minHeight: 54,
    borderBottomWidth: 2,
    borderBottomColor: "#c7c4ba",
    paddingHorizontal: 15,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pressed: { backgroundColor: "#d8e4eb" },
  name: { color: COLORS.ink, fontFamily: "Anton_400Regular", fontSize: 18 },
  original: {
    color: "#5f6669",
    fontFamily: "Courier New",
    fontSize: 10,
    marginTop: 2,
  },
  arrow: { color: COLORS.red, fontSize: 20 },
  empty: {
    color: "#5f6669",
    fontFamily: "Courier New",
    fontSize: 12,
    padding: 16,
  },
  notice: {
    color: COLORS.yellow,
    fontFamily: "Courier New",
    fontSize: 11,
    marginTop: 10,
  },
});
