import { StyleSheet } from "react-native";
import { COLORS } from "../constants/theme";

export default StyleSheet.create({
  area: { marginHorizontal: 20, marginBottom: 22 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 8,
  },
  title: {
    color: COLORS.yellow,
    fontFamily: "Anton_400Regular",
    letterSpacing: 0.5,
    fontSize: 16,
  },
  count: {
    color: COLORS.muted,
    fontFamily: "Courier New",
    fontSize: 10,
    fontWeight: "700",
  },
  hintCard: {
    backgroundColor: COLORS.blue,
    borderWidth: 3,
    borderColor: COLORS.ink,
    padding: 12,
    marginBottom: 8,
    shadowColor: COLORS.yellow,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  attempt: {
    color: "#d7e8fb",
    fontFamily: "Courier New",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  label: {
    color: "#d7e8fb",
    fontFamily: "Courier New",
    fontSize: 10,
    textTransform: "uppercase",
    marginTop: 6,
  },
  value: {
    color: "#fff",
    fontFamily: "Anton_400Regular",
    fontSize: 19,
    lineHeight: 23,
    marginTop: 2,
  },
  available: {
    minHeight: 68,
    backgroundColor: COLORS.panelSoft,
    borderWidth: 3,
    borderColor: COLORS.ink,
    borderStyle: "dashed",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 8,
  },
  availableCopy: { flex: 1 },
  availableTitle: {
    color: COLORS.yellow,
    fontFamily: "Anton_400Regular",
    fontSize: 15,
    letterSpacing: 0.5,
  },
  availableText: {
    color: COLORS.paper,
    fontFamily: "Courier New",
    fontSize: 10,
    marginTop: 2,
  },
  pressed: { opacity: 0.75 },
  locked: {
    minHeight: 70,
    borderWidth: 2,
    borderColor: COLORS.paper,
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 12,
  },
  lockedMark: { color: COLORS.yellow, fontSize: 28 },
  lockedText: {
    color: COLORS.muted,
    fontFamily: "Courier New",
    fontSize: 11,
    flex: 1,
    lineHeight: 16,
  },
  next: {
    color: COLORS.muted,
    fontFamily: "Courier New",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 8,
  },
});
